version: '3.7'

services:

  bookstore_react:
    build: .
    container_name: bookstore_react
    volumes:
      - .:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm start